# Site settings
title: The Last blog
description: >-
  He's writing his experience, mistakes, daily-rants in The Last Blog feel free to, contact him <a href="https://www.instagram.com/paramount.udbhav/">@instagram</a>.
lang: en-US
timezone: Asia/Kolkata
image: assets/img/profile.png 
repo: https://github.com/udbhavc
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Udbhav Chitransh
  bio: >-
    The minimalist website, light and dark mode support, for running a personal site and blog, 
    meet <a href="https://www.instagram.com/paramount.udbhav/">@instagram</a>.
  username: udbhavc
  email: udbhavchitransh@gmail.com
  email2: 2019umt1269@mnit.ac.in
  avatar: /assets/img/avatar.jpg

# Url settings
url: ""
baseurl: "/blog-personal"
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles
